version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # REST API
      - "3001:3001"  # gRPC server
    depends_on:
      - postgres
    environment:
      - APP_DATABASE_URL=postgresql://postgres:password@postgres:5432/rust_jwt_db
      - RUST_LOG=info
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rust_jwt_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: