services:
  - type: web
    name: server
    env: rust
    buildCommand: |
      # Make build scripts executable
      chmod +x scripts/*.sh
      # Run the build script
      ./scripts/build.sh
    startCommand: ./target/release/server
    envVars:
      - key: RENDER
        value: false
      - key: ENABLE_GRPC
        value: true
    runtime: rust